[package]
name = "json2pb"
version = "0.1.0"
authors = ["ronaldoliu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.2"
nom = "6.0.0-alpha1"
